1.2.0 dbquery from standard input hack for using sbinstall without sqlite not zero exit codes on errors

diff --git a/spm b/spm
--- a/spm
+++ b/spm
@@ -11,7 +11,7 @@ class SpmCmdVersion extends SpmCmd
 {
     public function executeNonSugar()
     {
-        echo "1.1.1\n";
+        echo "1.2.0\n";
     }
 }
 
@@ -29,7 +29,7 @@ Usage:
     spm upload <id_name>[-<version>]
     spm remove <id_name>[-<version>]
     spm repair
-    spm dbquery <sql>
+    spm dbquery [<sql>]
     spm check
     spm file <file1> [<file2> ...]
     spm create
@@ -90,8 +90,8 @@ spm repair
     Options:
         -v - show output
 
-spm dbquery <sql>
-    Run SQL-query on SugarCRM database.
+spm dbquery [<sql>]
+    Run SQL-query on SugarCRM database. If sql not specified, standard input will be read/\.
 
 spm check
     Search conflicts between installed packages.
@@ -180,6 +180,8 @@ class Spm
     public $spmPath;
     public $sandboxFile = '.spmsandbox';
     public $packagesOverwrites = array();
+    public $packagesInStaging = array();
+    public $packagesAvailable = array();
 
     /**
      * Simple method to find conflicts. Use it if `check` doesn't work.
@@ -624,6 +626,7 @@ class Spm
     {
         $pm = new PackageManager();
         $packs = $pm->getPackagesInStaging();
+        $this->packagesInStaging = array();
         $this->getDb()->exec("DROP TABLE IF EXISTS stage");
         $this->getDb()->exec("CREATE TABLE stage (id_name TEXT COLLATE NOCASE, version TEXT, filename TEXT, type TEXT)");
         $stmt = $this->getDb()->prepare("INSERT INTO stage (id_name, version, filename, type) VALUES (:id_name, :version, :filename, :type)");
@@ -646,6 +649,12 @@ class Spm
                     $filename = hashToFile($pack['file']);
                     $type = $manifest['type'];
                     $stmt->execute();
+                    $this->packagesInStaging["$id_name-$version"] = array(
+                        'id_name' => $id_name,
+                        'version' => $version,
+                        'filename' => $filename,
+                        'type' => $type,
+                    );
                 }
                 else {
                     echo "Warning: $target_manifest not exists while update stage\n";
@@ -679,6 +688,7 @@ class Spm
                     foreach($packs as $key => $pack) {
                         extract($pack);
                         $stmt->execute();
+                        $this->packagesAvailable[] = $pack;
                     }
                 }
                 else {
@@ -915,8 +925,16 @@ class Spm
     protected function getDb()
     {
         if(!$this->db) {
-            $this->db = new PDO('sqlite::memory:');
-            $this->db->sqliteCreateCollation('NATURAL_CMP', 'strnatcmp');
+            try {
+                $this->db = new PDO('sqlite::memory:');
+                $this->db->sqliteCreateCollation('NATURAL_CMP', 'strnatcmp');
+            }
+            catch(PDOException $e) {
+                echo "Connection to sqlite failed\n";
+                $this->db = new SpmPDO();
+                $this->db->spm = $this;
+                $this->db->lastException = $e;
+            }
         }
         return $this->db;
     }
@@ -924,8 +942,16 @@ class Spm
     protected function getUserDb()
     {
         if(!$this->userDb) {
-            $this->userDb = new PDO('sqlite::memory:');
-            $this->userDb->sqliteCreateCollation('NATURAL_CMP', 'strnatcmp');
+            try {
+                $this->userDb = new PDO('sqlite::memory:');
+                $this->userDb->sqliteCreateCollation('NATURAL_CMP', 'strnatcmp');
+            }
+            catch(PDOException $e) {
+                echo "Connection to sqlite failed\n";
+                $this->userDb = new SpmPDO();
+                $this->userDb->spm = $this;
+                $this->userDb->lastException = $e;
+            }
         }
         return $this->userDb;
     }
@@ -1391,6 +1417,145 @@ class Spm
     }
 }
 
+/**
+ * Dummy used when sqlite is unavailable
+ * UpdateStage supported only
+ */
+class SpmPDO
+{
+    public $lastException;
+    public $spm;
+
+    public function query($statement) {
+        throw $this->lastException;
+    }
+
+    public function quote($string) {
+        throw $this->lastException;
+    }
+
+    public function exec($statement)
+    {
+        if(in_array($statement, array(
+              "DROP TABLE IF EXISTS stage"
+            , "CREATE TABLE stage (id_name TEXT COLLATE NOCASE, version TEXT, filename TEXT, type TEXT)"
+            , "DROP TABLE IF EXISTS available"
+            , "CREATE TABLE available (id_name TEXT COLLATE NOCASE, version TEXT, filename TEXT)"
+        ))) {
+            return;
+        }
+        throw $this->lastException;
+    }
+
+    public function prepare($statement, $driver_options = array())
+    {
+        if($statement == "INSERT INTO stage (id_name, version, filename, type) VALUES (:id_name, :version, :filename, :type)") {
+            return new DummyStatement();
+        }
+        if($statement == SelectFromStageStatement::STATEMENT) {
+            $stmt = new SelectFromStageStatement();
+            $stmt->spm = $this->spm;
+            return $stmt;
+        }
+        if($statement == SelectOneFromStageStatement::STATEMENT) {
+            $stmt = new SelectOneFromStageStatement();
+            $stmt->spm = $this->spm;
+            return $stmt;
+        }
+        if($statement == "INSERT INTO available (id_name, version, filename) VALUES (:id_name, :version, :filename)") {
+            return new DummyStatement();
+        }
+        if($statement == SelectFromAvailableStatement::STATEMENT) {
+            $stmt = new SelectFromAvailableStatement();
+            $stmt->spm = $this->spm;
+            return $stmt;
+        }
+        throw $this->lastException;
+    }
+}
+
+/**
+ * Dummy used when sqlite is unavailable.
+ * Do nothing.
+ */
+class DummyStatement
+{
+    public $spm;
+    public $params = array();
+
+    public function bindParam($parameter, &$variable) {
+        $this->params[$parameter] = $variable;
+    }
+
+    public function execute($input_parameters = array()) {
+        $this->params = array_merge($this->params, $input_parameters);
+    }
+}
+/**
+ * Dummy used to update stage when sqlite is unavailable
+ */
+class SelectFromStageStatement extends DummyStatement
+{
+    const STATEMENT = "SELECT id_name, version, filename, type FROM stage WHERE id_name = :id_name AND (version = :version OR :version IS NULL) ORDER BY version COLLATE NATURAL_CMP DESC";
+
+    public function fetchAll()
+    {
+        $result = array();
+        foreach($this->spm->packagesInStaging as $pack) {
+            $id = $pack['id_name'];
+            $version = $pack['version'];
+            if($id != $this->params[':id_name'] || ($this->params[':version'] !== null && $version != $this->params[':version'])) {
+                continue;
+            }
+            $result[$version] = $pack;
+        }
+        uksort($result, "strnatcmp");
+        $result = array_reverse($result);
+        return $result;
+    }
+}
+class SelectOneFromStageStatement extends DummyStatement
+{
+    const STATEMENT = "SELECT 1 FROM stage WHERE id_name = :id_name AND version = :version LIMIT 1";
+
+    public function fetchAll()
+    {
+        $result = array();
+        foreach($this->spm->packagesInStaging as $pack) {
+            $id = $pack['id_name'];
+            $version = $pack['version'];
+            if($id != $this->params[':id_name'] || ($this->params[':version'] !== null && $version != $this->params[':version'])) {
+                continue;
+            }
+            $result[] = array('1' => 1);
+        }
+        return $result;
+    }
+}
+class SelectFromAvailableStatement extends DummyStatement
+{
+    const STATEMENT = "SELECT version, filename FROM available WHERE id_name = :id_name AND (version = :version OR :version IS NULL) ORDER BY version COLLATE NATURAL_CMP DESC LIMIT 1";
+
+    public function fetch()
+    {
+        $result = array();
+        foreach($this->spm->packagesAvailable as $pack) {
+            $id = $pack['id_name'];
+            $version = $pack['version'];
+            if($id != $this->params[':id_name'] || ($this->params[':version'] !== null && $version != $this->params[':version'])) {
+                continue;
+            }
+            $result[$version] = $pack;
+        }
+        uksort($result, "strnatcmp");
+        $result = array_reverse($result);
+        if(!empty($result)) {
+            return reset($result);
+        }
+        return null;
+    }
+}
+
 class DependenciesException extends Exception {
 }
 
@@ -1593,8 +1758,21 @@ class SpmCmdDbquery extends SpmCmd
 {
     public function execute()
     {
-        list($subjects, $options) = self::getArgvParams(1, array());
-        $this->spm->dbquery(reset($subjects));
+        list($subjects, $options) = self::getArgvParams(false, array());
+        if(count($subjects) > 1) {
+            array_shift($subjects);
+            throw new Exception("Unknown option ".implode(' ', $subjects));
+        }
+        if(empty($subjects)) {
+            $sql = '';
+            while($line = fgets(STDIN)) {
+              $sql .= $line."\n";
+            }
+        }
+        else {
+            $sql = reset($subjects);
+        }
+        $this->spm->dbquery($sql);
     }
 }
 
@@ -1848,7 +2026,7 @@ if(!defined('SUGARCRM_PRE_INSTALL_FILE'))
 $cmd = SpmCmd::getCmdFromCli();
 if(!$cmd) {
     echo "Unknown command. Run `spm help`.\n";
-    exit;
+    exit(2);
 }
 if(method_exists($cmd, 'executeNonSugar')) {
     try {
@@ -1856,7 +2034,7 @@ if(method_exists($cmd, 'executeNonSugar')) {
     }
     catch (Exception $e) {
         echo $e->getMessage(),"\n";
-        exit;
+        exit(3);
     }
 }
 if(!method_exists($cmd, 'execute')) {
@@ -1864,7 +2042,7 @@ if(!method_exists($cmd, 'execute')) {
 }
 if(!Spm::enterSugar()) {
     echo "SugarCRM root not found.\n";
-    exit;
+    exit(4);
 }
 
 require_once('ModuleInstall/PackageManager/PackageManager.php');
@@ -2178,8 +2356,13 @@ class SpmRepairAndClear extends RepairAndClear
 
 try {
     $cmd->execute();
+    $error = null;
 }
 catch (Exception $e) {
     echo $e->getMessage(),"\n";
+    $error = true;
 }
 Spm::cleanupSugar();
+if($error) {
+    exit(1);
+}
